# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('matcher', models.CharField(choices=[('matcher1', 'Matcher1'), ('matcher2', 'Matcher2')], max_length=10)),
                ('status', models.CharField(default='CREATED', max_length=10)),
                ('percent_complete', models.FloatField(default=0.0)),
            ],
        ),
    ]
